// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressPlay;

namespace PressPlay.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190719150549_GreaterMigration")]
    partial class GreaterMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PressPlay.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumTitle");

                    b.Property<int>("ArtistId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("RecordLabel");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album");

                    b.HasData(
                        new { AlbumId = 1, AlbumTitle = "KOD", ArtistId = 1, ImageUrl = "https://media.pitchfork.com/photos/5ad8b39b5fadaa7e89cfd808/2:1/w_1000/KOD%20J.%20Cole.jpg", RecordLabel = "DreamVille" },
                        new { AlbumId = 2, AlbumTitle = "Sweetener", ArtistId = 2, ImageUrl = "https://www.udiscovermusic.com/wp-content/uploads/2018/06/Ariana-Grande-No-Tears-Left-To-Cry-packshot-cropped-web-optimised-1000.jpg", RecordLabel = "Republic Records" },
                        new { AlbumId = 3, AlbumTitle = "missundaztood", ArtistId = 3, ImageUrl = "https://images-na.ssl-images-amazon.com/images/I/81GGshIlE4L._SL1200_.jpg", RecordLabel = "Arista Records" },
                        new { AlbumId = 4, AlbumTitle = "Rust In Peace", ArtistId = 4, ImageUrl = "https://i.ytimg.com/vi/SW6uObWJRH4/maxresdefault.jpg", RecordLabel = "Capitol Records" },
                        new { AlbumId = 5, AlbumTitle = "4 Your Eyes Only", ArtistId = 1, ImageUrl = "", RecordLabel = "Dreamville" },
                        new { AlbumId = 6, AlbumTitle = "Thank U, Next ", ArtistId = 2, ImageUrl = "", RecordLabel = "Republic Records" },
                        new { AlbumId = 7, AlbumTitle = "Hurts 2B Human", ArtistId = 3, ImageUrl = "", RecordLabel = "Arista Records" },
                        new { AlbumId = 8, AlbumTitle = "Dystopia", ArtistId = 4, ImageUrl = "", RecordLabel = "Capitol Records" }
                    );
                });

            modelBuilder.Entity("PressPlay.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistName");

                    b.Property<string>("ImageUrl");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new { ArtistId = 1, ArtistName = "J Cole", ImageUrl = "https://i.ytimg.com/vi/UhD66RY3jt4/maxresdefault.jpg" },
                        new { ArtistId = 2, ArtistName = "Ariana Grande", ImageUrl = "https://www.androidred.com/wp-content/uploads/2019/01/Ariana-Grande-Special-background.jpg" },
                        new { ArtistId = 3, ArtistName = "Pink", ImageUrl = "https://ewscripps.brightspotcdn.com/dims4/default/ad6bfcf/2147483647/strip/true/crop/640x360+0+60/resize/1280x720!/quality/90/?url=https%3A%2F%2Fsharing.wxyz.com%2Fsharescnn%2Fphoto%2F2018%2F08%2F23%2FGettyImages-1000155580_1535076197337_95575003_ver1.0_640_480.jpg" },
                        new { ArtistId = 4, ArtistName = "Megadeth", ImageUrl = "https://images.wallpaperscraft.com/image/megadeth_hair_jackets_graphics_tie_6137_1280x720.jpg" }
                    );
                });

            modelBuilder.Entity("PressPlay.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<int>("Duration");

                    b.Property<string>("Link");

                    b.Property<string>("SongTitle");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Song");

                    b.HasData(
                        new { SongId = 1, AlbumId = 1, Duration = 132, Link = "https://www.youtube.com/watch?v=2hMy0rnHQv0", SongTitle = "Motiv8" },
                        new { SongId = 2, AlbumId = 2, Duration = 182, Link = "https://www.youtube.com/watch?v=-_aGvdfLTKY", SongTitle = "Nasa" },
                        new { SongId = 3, AlbumId = 3, Duration = 191, Link = "https://www.youtube.com/watch?v=mW1dbiD_zDk", SongTitle = "Get the Party Started" },
                        new { SongId = 4, AlbumId = 4, Duration = 299, Link = "https://www.youtube.com/watch?v=Lcm9qqo_qB0", SongTitle = "Tornado of Souls" }
                    );
                });

            modelBuilder.Entity("PressPlay.Models.Album", b =>
                {
                    b.HasOne("PressPlay.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PressPlay.Models.Song", b =>
                {
                    b.HasOne("PressPlay.Models.Album", "Album")
                        .WithMany("Song")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
